### ISSUE TITLE
Build failure, any suggestion pls

### ISSUE THREAD

**Issue by ramrattle** [stratum/stratum#1078] opened 2022-12-23 16:12 UTC
**Describe the bug**
Startum build is failing with below Error

bazel-out/k8-fastbuild/bin/external/com_github_openconfig_gnmi_proto/gnmi/gnmi.pb.h:8040:23: note: declared here
 inline ::gnmi::Error* SubscribeResponse::mutable_error() {
                       ^~~~~~~~~~~~~~~~~
ERROR: /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/local_barefoot_bin/BUILD:109:8: Writing: bazel-out/k8-fastbuild/bin/external/local_barefoot_bin/bf_binary_files.tar failed: missing input file 'external/local_barefoot_bin/barefoot-bin/bin/credo_firmware.bin', owner: '@local_barefoot_bin//:barefoot-bin/bin/credo_firmware.bin'
Target //stratum/hal/bin/barefoot:stratum_bfrt_deb failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/local_barefoot_bin/BUILD:109:8 Writing: bazel-out/k8-fastbuild/bin/external/local_barefoot_bin/bf_binary_files.tar failed: 1 input file(s) do not exist
INFO: Elapsed time: 634.606s, Critical Path: 33.06s
INFO: 2407 processes: 401 internal, 2006 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Environment**

If building from source:
bazel 4.2.3
Compilation is failing in all 4 methods

compiling from linux machine with 5.8.0-45-generic
sde verion used : 9.7.0, 9.10.0, 9.11. 0 (same failure for all sde versions)

**Comment by pudelkoM** [comment] 2023-01-04 05:45
This should have the same `credo_firmware.bin` root cause.
Closed by #1080

**Closed by pudelkoM** 2023-01-04 05:45 UTC
Labels: bug
